### ISSUE TITLE
Detection with webcam

### ISSUE THREAD

**Issue by topiabu2** [Gokul-GMenon/cylinder-detection-yolov5#1]
How can I do detection and counting with webcam as the source?

**Comment by Gokul-GMenon** [comment]
You can refer to the readme file provided. It gives instructions on how to make the project work. Here's a quick rundown:
-  You have to clone the yolov5 repo whose link has been provided.
-  You can then replace the detect.py file in the repo with the custom file given.
-  Run the detect_cylinder.py file with source value as zero (0) for using the webcam.
-  By editing the detection.py file, you can see the area responsible for drawing the bounding boxes and keep a counter to count the values.
